name: 'SDKMAN action'
description: 'Use SDKMAN in your GitHub workflows'
author: 'Sébastien Perpignane'

branding:
  icon: 'zap'
  color: 'red'

inputs:
  sdkman-install-dir:
    required: false
    description: 'Where sdkman will be installed. Default value is <user directory>/sdkman_gh_actions'

outputs:
  sdkman_install_dir:
    description: 'Where sdkman was installed'
runs:
  using: 'node16'
  main: 'dist/index.js'
