name: 'Setup javastep'
description: 'generate a script that allows to run github workflow steps written in java. requires java 24. usage -> shell: javastep {0}'
author: 'Sébastien Perpignane'

branding:
  icon: 'zap'
  color: 'red'
  
runs:
  using: 'composite'
  steps:
    - name: 'create script'
      shell: bash
      run: |
        run_step_path="/tmp/_java_step_"
        mkdir "$run_step_path"
        cp ${{ github.action_path }}/resources/javastep "$run_step_path"
        echo "$run_step_path" >> $GITHUB_PATH
