name: 'SDKMAN action'
description: 'Use SDKMAN in your GitHub workflows'
author: 'Sébastien Perpignane'

branding:
  icon: 'zap'
  color: 'red'

inputs:
  subcommand:
    description: 'The Groovy SDK version to setup'
    required: true
  sdkman-install-dir:
    description: 'Where sdkman will be installed. Default value is <user directory>/sdkman_gh_actions'
runs:
  using: 'node16'
  main: 'dist/index.js'
