name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  groovy-version:
    description: 'The Groovy SDK version to setup. If no version is specified, the latest stable version will be selected automatically.'
  sdkman-install-dir:
    description: 'Where sdkman will be installed'
runs:
  using: 'node16'
  main: 'dist/index.js'
