name: 'Check setup-groovy/dist/'

on:
  push:
    branches:
      - main
    paths:
      - "setup-groovy/**"
      - "!**.md"
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  check-dist-groovy:
    uses: './.github/workflows/check-dist.yml'
    with:
      module: 'setup-groovy'
