name: 'groovy step'

on:
  workflow_dispatch:

jobs:
  test-setup-groovy:
    runs-on: ubuntu-latest
    steps:
      - name: 'setup-groovy action'
        uses: sebastien-perpignane/actions/setup-groovy@main
        with:
          groovy-version: 4.0.27

      - name: groovy step
        shell: groovy {0}
        run: |
          println "groovy rocks"
