name: 'groovy step'

on:
  workflow_dispatch:

jobs:
  groovy-step:
    runs-on: ubuntu-latest
    steps:
      - name: setup groovystep
        uses: sebastien-perpignane/actions/setup-groovystep@main
      - name: groovy step
        shell: groovystep {0}
        run: |
          
          println "groovy rocks"
          
          addEnv("my_name", "seb")

      - name: display env
        shell: bash
        run: |
          echo $my_name
