name: 'groovy step'

on:
  workflow_dispatch:

jobs:
  groovy-step:
    runs-on: ubuntu-latest
    steps:
      - name: 'setup-groovy action'
        uses: sebastien-perpignane/actions/setup-groovy@main
        with:
          groovy-version: 4.0.27

      - name: groovy step
        shell: groovy {0}
        run: |
          
          def envFileName = System.getenv("GITHUB_ENV")
          println "envFileName: $envFileName"
          def envFile = new File(envFileName)
          
          def addEnv = { String n, String v ->
            def eol = System.lineSeparator()
            envFile.append("$n=$v$eol")
          }
          
          println "groovy rocks"
          
          addEnv("my_name", "seb")

      - name: display env
        shell: bash
        run: |
          echo $my_name
