name: 'groovy step'

on:
  workflow_dispatch:

jobs:
  groovy-step:
    runs-on: ubuntu-latest
    steps:
#      - name: 'setup-groovy action'
#        uses: sebastien-perpignane/actions/setup-groovy@main
#        with:
#          groovy-version: 4.0.27
#
#      - name: 'prepare base script'
#        shell: bash
#        run: |
#          echo '
#            abstract class StepScript extends Script {
#
#              String envFileName = System.getenv("GITHUB_ENV")
#              File envFile = new File(envFileName)
#
#              String outFileName = System.getenv("GITHUB_OUTPUT")
#              File outFile = new File(outFileName)
#
#              static String eol = System.lineSeparator()
#
#              def addEnv = { String k, String v ->
#              println "adding $k, $v to GITHUB_ENV"
#              appendToKeyValueFile(envFile, k, v)
#            }
#
#              def addOut = { String k, String v ->
#              println "adding $k, $v to GITHUB_OUT"
#              appendToKeyValueFile(outFile, k, v)
#            }
#
#              static void appendToKeyValueFile(File file, String key, String value) {
#              def row = "$key=$value$eol"
#              file.append(row)
#            }
#
#              def run() {
#              def result = runScript()
#              println "env file after"
#              println envFile.text
#
#              println "out file after"
#              println outFile.text
#
#              return result
#            }
#
#              abstract def runScript()
#
#          }' > StepScript.groovy
#
#      - name: setup-groovy-step
#        shell: bash
#        run: |
#          mkdir temp_bin
#          echo '#!/usr/bin/env sh
#          groovy -b StepScript "$1"
#          ' > temp_bin/groovystep
#
#          chmod +x temp_bin/groovystep
#
#          cat temp_bin/groovystep
#
#          echo "$(pwd)/temp_bin" > $GITHUB_PATH

      - name: setup groovystep
        uses: sebastien-perpignane/actions/setup-groovystep@main
      - name: groovy step
        shell: groovystep {0}
        run: |
          
          println "groovy rocks"
          
          addEnv("my_name", "seb")

      - name: display env
        shell: bash
        run: |
          echo $my_name
