name: 'Publish setup-sdkman'

on:
  workflow_dispatch:

jobs:
  publish-setup-sdkman:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 18.x
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18.x
          cache-dependency-path: '${{ inputs.module }}/package-lock.json'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@sebastien-perpignane'
          cache: 'npm'

      - name: "publish"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          npm publish
