name: 'build-test'
on: # rebuild any PRs and main branch changes
  
  workflow_dispatch:
    inputs:
      module:
        description: module to be tested (setup-groovy, setup-sdkman)
        required: true
        type: choice
        options:
          - "setup-sdkman"
          - "setup-groovy"
  workflow_call:
    inputs:
      module:
        description: module to be tested (setup-groovy, setup-sdkman)
        type: string
        required: true

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./${{ inputs.module }}

    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.x
          cache-dependency-path: '${{ inputs.module }}/package-lock.json'
          cache: 'npm'
      - run: |
          npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          npm run all
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: 'Run setup-groovy action'
        if: ${{ inputs.module == 'setup-groovy' }}
        uses: ./setup-groovy/
        with:
          groovy-version: 4.0.13
      - name: 'Run setup-sdkman action'
        if: ${{ inputs.module == 'setup-sdkman' }}
        uses: ./setup-sdkman/
