name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./setup-groovy

    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          npm run all
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: 'Run setup-groovy action'
        uses: ./setup-groovy/
        with:
          groovy-version: 4.0.13
