name: 'build-test-setup-groovy'

on:
  push:
    branches:
      - main
    paths:
      - "setup-groovy/**"
      - '!**.md'
  pull_request:
    paths:
      - "setup-groovy/**"
      - '!**.md'
  workflow_dispatch:

jobs:
  test-setup-groovy:
    uses: './.github/workflows/test.yml'
    with:
      module: 'setup-groovy'